# sense_dict including implicits and explicits
sense_dict = {
    'After all': ['Contingency.Cause+Belief.Reason+Belief', 'Expansion.Conjunction', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'After that': ['Temporal.Asynchronous.Succession'], 
    'Along with': ['Expansion.Conjunction'], 
    'And then': ['Expansion.Disjunction'], 
    'As a consequence': ['Contingency.Cause.Result'], 
    'As a result': ['Contingency.Cause.Result', 'Contingency.Cause+Belief.Result+Belief', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'As an alternative': ['Expansion.Disjunction'], 
    'As it turns out': ['Contingency.Cause.Result', 'Expansion.Conjunction'], 
    'As part of that': ['Expansion.Instantiation.Arg2-as-instance'], 
    'As such': ['Contingency.Cause+Belief.Result+Belief', 'Contingency.Cause.Result'], 
    'As well': ['Comparison.Similarity', 'Expansion.Conjunction'], 
    'At that point': ['Temporal.Synchronous'], 
    'At that time': ['Temporal.Synchronous'], 
    'At the same time': ['Temporal.Synchronous', 'Expansion.Conjunction'], 
    'At the time': ['Temporal.Synchronous'], 
    'Because of that': ['Contingency.Cause.Result'], 
    'Before that': ['Temporal.Asynchronous.Succession'], 
    'But then again': ['Comparison.Concession.Arg2-as-denier'], 
    'But then': ['Comparison.Concession.Arg2-as-denier'], 
    'By comparison': ['Comparison.Contrast', 'Comparison.Concession.Arg2-as-denier', 'Expansion.Conjunction'], 
    'By contrast': ['Comparison.Contrast', 'Comparison.Concession.Arg2-as-denier'], 
    'By doing so': ['Expansion.Manner.Arg1-as-manner'], 
    'By the way': ['Comparison:Contrast', 'Expansion.Conjunction'], 
    'By then': ['Temporal.Asynchronous.Succession|Contingency.Cause.Reason', 'Temporal.Asynchronous.Succession'], 
    'Despite this': ['Comparison.Concession.Arg2-as-denier'], 
    'During that time': ['Temporal.Synchronous'], 
    'Even before then': ['Temporal.Asynchronous.Succession|Comparison.Concession.Arg2-as-denier'], 
    'Even before': ['Temporal.Asynchronous.Precedence|Comparison.Concession.Arg1-as-denier'], 
    'Even then': ['Temporal.Asynchronous.Precedence|Comparison.Concession.Arg2-as-denier'], 
    'For example': ['Expansion.Instantiation.Arg2-as-instance', 'Contingency.Cause.Reason', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'For instance': ['Expansion.Instantiation.Arg2-as-instance', 'Expansion.Conjunction', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'For one thing': ['Contingency.Cause.Reason', 'Expansion.Conjunction', 'Expansion.Instantiation.Arg2-as-instance', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'For one': ['Expansion.Instantiation.Arg2-as-instance'], 
    'For that purpose': ['Contingency.Purpose.Arg1-as-goal'], 
    'For that reason': ['Contingency.Cause.Result'], 
    'In addition': ['Expansion.Conjunction', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'In any case': ['Comparison.Concession.Arg2-as-denier'], 
    'In any event': ['Expansion.Conjunction', 'Expansion.Level-of-detail.Arg1-as-detail'], 
    'In comparison': ['Comparison.Contrast'], 
    'In contrast': ['Comparison.Contrast'], 
    'In essence': ['Expansion.Conjunction'], 
    'In fact': ['Comparison.Concession.Arg2-as-denier', 'Comparison.Contrast', 'Expansion.Conjunction', 'Expansion.Instantiation.Arg2-as-instance', 'Expansion.Level-of-detail.Arg1-as-detail', 'Expansion.Level-of-detail.Arg2-as-detail', 'Contingency.Cause+Belief.Reason+Belief', 'Contingency.Cause+Belief.Result+Belief', 'Contingency.Cause.Reason', 'Contingency.Cause.Result', 'Expansion.Equivalence'], 
    'In general': ['Expansion.Level-of-detail.Arg1-as-detail'], 
    'In more detail': ['Expansion.Level-of-detail.Arg2-as-detail'], 
    'In other words': ['Expansion.Equivalence', 'Comparison.Similarity', 'Contingency.Cause.Reason', 'Contingency.Cause.Result', 'Expansion.Conjunction', 'Expansion.Level-of-detail.Arg1-as-detail', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'In particular': ['Expansion.Instantiation.Arg2-as-instance', 'Expansion.Level-of-detail.Arg2-as-detail', 'Expansion.Conjunction'], 
    'In response': ['Contingency.Cause.Result', 'Expansion.Conjunction'], 
    'In short': ['Expansion.Level-of-detail.Arg1-as-detail', 'Contingency.Cause+SpeechAct.Result+SpeechAct', 'Contingency.Cause.Reason', 'Contingency.Cause.Result', 'Expansion.Conjunction', 'Expansion.Equivalence', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'In sum': ['Expansion.Level-of-detail.Arg1-as-detail', 'Expansion.Conjunction', 'Expansion.Equivalence', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'In the end': ['Comparison.Concession.Arg2-as-denier', 'Comparison.Contrast', 'Contingency.Cause.Result', 'Expansion.Conjunction', 'Expansion.Level-of-detail.Arg1-as-detail', 'Expansion.Level-of-detail.Arg2-as-detail', 'Temporal.Asynchronous.Precedence', 'Expansion.Equivalence'], 
    'In the meantime': ['Temporal.Asynchronous.Succession', 'Temporal.Synchronous|Comparison.Contrast', 'Temporal.Synchronous'], 
    'In the meanwhile': ['Temporal.Synchronous'], 
    'In this case': ['Expansion.Instantiation.Arg2-as-instance'], 
    'In this way': ['Contingency.Cause.Result'], 
    'In turn': ['Temporal.Asynchronous.Precedence', 'Contingency.Cause.Result', 'Expansion.Conjunction'], 
    'Later on': ['Temporal.Asynchronous.Precedence'], 
    'More accurately': ['Expansion.Substitution.Arg2-as-subst'], 
    'More specifically': ['Expansion.Level-of-detail.Arg2-as-detail'], 
    'More to the point': ['Expansion.Level-of-detail.Arg2-as-detail'], 
    'No matter': ['Comparison.Concession.Arg1-as-denier'], 
    'On the contrary': ['Comparison.Contrast', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'On the other hand': ['Comparison.Concession.Arg2-as-denier', 'Comparison.Contrast'], 
    'On the other': ['Comparison.Concession.Arg2-as-denier', 'Comparison.Contrast'], 
    'On the whole': ['Expansion.Conjunction', 'Expansion.Level-of-detail.Arg1-as-detail', 'Expansion.Level-of-detail.Arg2-as-detail'], 
    'Prior to this': ['Temporal.Asynchronous.Succession'], 
    'Since then': ['Temporal.Asynchronous.Precedence'], 
    'That is': ['Expansion.Equivalence', 'Expansion.Level-of-detail.Arg2-as-detail', 'Contingency.Cause.Reason', 'Contingency.Cause.Result', 'Expansion.Conjunction', 'Expansion.Level-of-detail.Arg1-as-detail'], 
    'To this end': ['Contingency.Cause.Result'], 
    "What's more": ['Expansion.Conjunction']
    }
